name = "qualcanvas-api"
main = "src/index.ts"
compatibility_date = "2024-12-01"
compatibility_flags = ["nodejs_compat"]

[vars]
JWT_SECRET = "qualcanvas-jwt-secret-change-in-production"
ALLOWED_ORIGINS = "https://qualcanvas.com"

[[d1_databases]]
binding = "DB"
database_name = "qualcanvas-db"
database_id = "2327a3cb-925e-4873-98c0-ef241093a8d1"
